version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mayla-telegrambot
    ports:
      - 27017:27017
    volumes:
      - ~/telegram:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root2022
